# Generated by Django 4.1 on 2022-08-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("breakfast", models.CharField(blank=True, default="", max_length=200)),
                ("lunch", models.CharField(blank=True, default="", max_length=200)),
                ("dinner", models.CharField(blank=True, default="", max_length=200)),
                ("snack", models.CharField(blank=True, default="", max_length=200)),
            ],
        ),
    ]
